### ISSUE TITLE
Out-of-memory error during server startup or export-heaptrack

### ISSUE THREAD

**Issue by mbalabin** [koute/memory-profiler#18]
I tried to profile my application. It allocates several gigabytes of memory at peak.

Recording process went well and a 5.2 Gb trace was generated. I tried to open the dump using "memory-profiler-cli server" command, but it segfaulted with "memory allocation of 21299200000 bytes failed" error. The same happened when i tried to export data using export-heaptrack.

I tried to use "memory-profiler-cli squeeze", and it did shrank the trace to 124M. I was able to open the new trace, but it seems to contain no sensible data. Accoding to the squeezed trace, only 72kb was allocated.

Could you please provide any advice on what to do next? Can I do anything besides running my program with less input data?

**Comment by koute** [comment]
Unfortunately right now loading a data file needs a lot of memory since everything needs to be loaded into memory. (The trace file contains the metadata for *every* allocation and is compressed, so it's *a lot* of data.)

What do you actually want to achieve?

The `squeeze` subcommand strips away all of the temporary allocations, so it's only useful for investigating memory leaks.

**Comment by mbalabin** [comment]
Memory consumption of my application is too high. I am trying to investigate the issue and find out where most memory is allocated. The final goal is to rewrite some data structures to reduce peak memory usage.

Memory leaks are not the issue (none are found), so it seems squeeze will not help me.
